authors = []
categories = [
    "astro-ph.GA",
    "astro-ph.HE",
    "astro-ph.SR",
    "physics.plasm-ph",
]
keywords_to_exclude = ["machine"]
keywords_to_include = [
    ["cosmic", "ray", ["turb", "magnet", "interstellar", "ISM", "feedback", "transport", "diffus", "stream"]],
]
