authors = []
categories = [
    "astro-ph.GA",
    "astro-ph.HE",
    "astro-ph.SR",
    "astro-ph.CO",
    "physics.plasm-ph",
    "physics.flu-dyn",
]
keywords_to_exclude = ["rmhd", "gr-mhd", "relativis", "tokamak", "machine"]
keywords_to_include = [
    "dynamo",
    ["scale", "amplif"],
]
