authors = []
categories = [
    "astro-ph.GA",
    "astro-ph.HE",
    "astro-ph.SR",
    "physics.plasm-ph",
    "physics.flu-dyn",
]
keywords_to_exclude = ["rmhd", "gr-mhd", "relativis", "tokamak", "machine"]
keywords_to_include = [
    "mhd",
    "chiral",
    "reconnect",
    ["magnet", ["prandtl", "reynolds", "helicit", "alfven", "turb", "dynamo", "amplif", "cascade", ["inertial", "range"]]],
]
