authors = []
categories = [
    "astro-ph.CO",
    "astro-ph.GA",
    "physics.plasm-ph",
    "hep-ph",
]
keywords_to_exclude = ["machine"]
keywords_to_include = [
    ["primordial", ["magnet", "dynamo", "helicit", "magnetogenes"]],
    ["cosmological", ["magnet", "dynamo", "helicit", "magnetogenes"]],
    ["early", "universe", ["magnet", "dynamo", "helicit"]],
    "magnetogenes",
    "biermann",
]
