authors = []
categories = [
    "astro-ph.GA",
    "astro-ph.SR",
]
keywords_to_exclude = ["machine"]
keywords_to_include = [
    ["star form", ["magnet", "turb", "mhd", "dynamo", "feedback", ["cosmic", "ray"]]],
    ["molecular", "cloud", ["magnet", "turb", "mhd", "collaps", "fragm"]],
    ["protost", ["magnet", "turb", "mhd", "disk", "outflow", "jet"]],
]
